name: 07 - Self Hosted Runner

on:
  push:
    branches: ["*"]

jobs:
  node-setup:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Start AWS Planning application
        run: |
          node index.js > app.log 2>&1 &
          echo $! > app.pid
          sleep 5

      - name: Test application
        run: |
          curl http://localhost:3000

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: List S3 buckets
        run: |
          aws s3 ls
          aws s3 mb s3://david.tejesvi.12345678
